export enum CategoryType {
  CONFERENCES = 'CONFERENCES',
  EXCURSIONS = 'EXCURSIONS',
  COMPETITIONS = 'COMPETITIONS',
  CAREER = 'CAREER',
  TRAININGS = 'TRAININGS',
  UNIVERSITY_LIFE = 'UNIVERSITY_LIFE',
  SCIENCE = 'SCIENCE',
  SPORTS = 'SPORTS'
} 